"""Remove unnecessary columns

Revision ID: 1e322fcf9b9b
Revises: bd79683ebb57
Create Date: 2024-12-10 21:45:13.904153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e322fcf9b9b'
down_revision: Union[str, None] = 'bd79683ebb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint('requests_user_id_fkey', 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'users', ['author_id'], ['id'])
    op.drop_column('requests', 'user_id')
    op.drop_column('requests', 'chatid')
    op.drop_column('requests', 'bottoken')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('bottoken', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('chatid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key('requests_user_id_fkey', 'requests', 'users', ['user_id'], ['id'])
    op.drop_column('requests', 'author_id')
    # ### end Alembic commands ###
